apiVersion: v2
name: litunovskiy-hw3-helm-chart
description: A Helm chart for Litunovskiy hw3

type: application

version: 1.0.0

appVersion: "1.16.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.2.27
