replicaCount: 1

image:
  repository: litvitnik/homework3
  pullPolicy: Always
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

properties:
  ENV_URL: jdbc:postgresql://litunovskiy-hw3-helm-chart-postgresql.hw3.svc.cluster.local:5432/maindb
  ENV_DRIVER_CLASS_NAME: org.postgresql.Driver
  ENV_DATABASE: postgresql
  ENV_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

# Used to override postgresql dependency chart values
global:
  postgresql:
    auth:
      username: "user1"
      password: "pass1"
      database: "maindb"